### ISSUE TITLE
Scheduler Roadmap

### ISSUE THREAD

**Issue by HaithemMosbahi** [HaithemMosbahi/full-calendar#9]
The aim of this ticket is to prepare a todo list of the features that are going to be implemented in future releases.

Scheduler V 1.x

- [x] A declarative web component that wraps the fullCalendar library 

- [x] Customize and configure the scheduler using properties

- [x] Dispatch events as they occur ( click on event, click on day, change view , etc )

- [x] Organize scheduler's events using categories 
    
   - [x] Show / Hide categories in the bottom of the scheduler

   - [x] Show / Hide events when selecting / deselecting a category 

  - [x] Coloration of events based on categories

 - [ ] Add custom properties API to style the scheduler 

Scheduler V 2.x

- [ ] Add default view, create and edit templates

- [ ] Support overriding view, create and edit templates

- [ ] Extensible Themes

- [ ] Add the ability to override categories template.

**Comment by HaithemMosbahi** [comment]
Hey man @rodzzlessa24 as we have discussed, I've just added the current state of scheduler's roadmap. I'm looking forward to your feedback. Feel free to suggest new features.
Actually, I've been thinking of keeping the 1.x version simple with only basic functionalities and moving the more advanced features like adding view and edit templates to version 2.x

**Comment by threeaccents** [comment]
This is great man. I can get started adding the default views.

**Comment by HaithemMosbahi** [comment]
Yes that would be great. I've already added view and edit element ( only element's structure ).
However, I've been thinking of moving these elements to a new branch.
As described above, I think of keeping the default views to version 2 and release a new minor version soon.
So you can start working on this feature in new branch.

**Comment by HaithemMosbahi** [comment]
Do you have any other features in your mind ?

**Comment by threeaccents** [comment]
I was actually just thinking on working a bit on the new app to see if there is anything missing. One thing that we can maybe think about is not including the fullcalendar css theme by default.

**Comment by HaithemMosbahi** [comment]
Yes, I agree with you. Then, we can support one or more additional themes like Default theme, Material theme, etc. 
A new feature has been added : Extensible Themes

**Comment by HaithemMosbahi** [comment]
hey man I've just created a new branch **scheduler-v2**, you can use it in the development of the default views feature

**Comment by HaithemMosbahi** [comment]
I'm looking forward to release a new version by the end of the week that will include organizing events using categories.
Also, we should consider improving element's testing and documentation.

**Comment by HaithemMosbahi** [comment]
hey @rodzzlessa24, I've created a team on slack for this component. I think it's better to chat and discuss ideas there. I've sent you an invitation, here is the url : https://scheduler-component.slack.com/
**Upadte** : Well I've changed my mind and I've decided to go with gitter over slack, I think it's more suitable to github based project. I've sent you an invitation as well ^^

**Comment by threeaccents** [comment]
@HaithemMosbahi Hey man I don't think I got the gitter invite. I've been writing to you on Slack
